### PR TITLE
Add module-info

### PR DESCRIPTION
**Pull request by bowbahdoe**
This adds a module-info using moditect.

This is required to use this with jlink

## Before
bad

## After
demo

### CODE REVIEW

**Comment by bowbahdoe** [comment]
@enepomnyaschih  Anything I can do to help you have time to get to this?

**Comment by bowbahdoe** [comment]
@enepomnyaschih I'll buy you a pizza

**Comment by enepomnyaschih** [comment]
Sorry for a delay. I'm trying to redeploy the artifacts with your changes applied. It may take a few days, because I barely have any time to work on this project.

**Comment by enepomnyaschih** [comment]
Deployed as [4.2.1](https://mvnrepository.com/artifact/com.github.squigglesql/squigglesql/4.2.1).

**Comment by bowbahdoe** [comment]
@enepomnyaschih Send me a venmo or address for that pizza

**Comment by enepomnyaschih** [comment]
Merged from https://github.com/squigglesql/squigglesql/pull/19

**Pull request closed without merging**
